### ISSUE TITLE
Return type mismatch between linked nodes: foreground, IMAGE != LATENT

### ISSUE THREAD

**Issue by robo-ranger** [kijai/ComfyUI-IC-Light#5]
I'm unable to get it working. The error message

Prompt outputs failed validation
ICLightConditioning:
- Return type mismatch between linked nodes: foreground, IMAGE != LATENT

appears. I've already updated ComfyUI, but the issue persists. Are there any additional steps beyond installing this node and placing the model in the models/unet folder that I need to take?

**Comment by AiSatan** [comment]
you probably just loaded workflow from readme - remove IC light conditioning node, add it again, now inputs will be correct latent type, convert images to latent with vae encode, worked for me

**Comment by kijai** [comment]
That's because I changed that node to work with latents instead of images, I have updated the workflows in the examples folder and they should have the new version of the node, but if you for some reason have the old node still, you can simply recreate it, either remove and re-add or right click and "Fix (recreate)", it should look like this:

![image](https://github.com/kijai/ComfyUI-IC-Light/assets/40791699/4b468d15-8bf3-4160-be82-8ffddf4d50dc)

**Comment by kijai** [comment]
> you probably just loaded workflow from readme - remove IC light conditioning node, add it again, now inputs will be correct latent type, convert images to latent with vae encode, worked for me

Good point, forgot to change those, did that now, thanks!

**Comment by robo-ranger** [comment]
Thank you very much!
